/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnTrackEditEnumerable : System.Collections.Generic.IEnumerable<GnTrackEdit>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnTrackEditEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnTrackEditEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnTrackEditEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnTrackEditEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnTrackEdit> System.Collections.Generic.IEnumerable<GnTrackEdit> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnTrackEditEnumerable(GnTrackEditProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnTrackEditEnumerable(GnTrackEditProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnTrackEditEnumerator GetEnumerator() {
    GnTrackEditEnumerator ret = new GnTrackEditEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnTrackEditEnumerator end() {
    GnTrackEditEnumerator ret = new GnTrackEditEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_count(swigCPtr);
    return ret;
  }

  public GnTrackEditEnumerator at(uint index) {
    GnTrackEditEnumerator ret = new GnTrackEditEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnTrackEditEnumerator getByIndex(uint index) {
    GnTrackEditEnumerator ret = new GnTrackEditEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
